_format_version: "3.0"

plugins:
  - name: rate-limiting
    config:
      minute: 1800
      second: 30
      policy: local
      fault_tolerant: true
      hide_client_headers: false

services:
  - name: games-service
    url: http://games:4001
    plugins:
      - name: rate-limiting
        config:
          minute: 600
          second: 10
          policy: local
          fault_tolerant: true
          hide_client_headers: false
    routes:
      - name: games-routes
        paths:
          - /games
        strip_path: true

  - name: wallets-service
    url: http://wallets:4002
    routes:
      - name: wallets-routes
        paths:
          - /wallets
        strip_path: true

  - name: games-ws
    url: http://games:4001
    routes:
      - name: games-ws-route
        paths:
          - /ws
        strip_path: true
